### ISSUE TITLE
Crashes on AOSP phone

### ISSUE THREAD

**Issue by inducer** [SamWhited/OpenShareLocationPlugin#4]
Hi there,

thanks for putting together this plugin. Unfortunately, it's unusable on my phone--it crashes with the following traceback:

```
03-21 14:29:47.652 D/AndroidRuntime(30624): Shutting down VM
03-21 14:29:47.662 E/AndroidRuntime(30624): FATAL EXCEPTION: main
03-21 14:29:47.662 E/AndroidRuntime(30624): Process: com.samwhited.opensharelocationplugin, PID: 30624
03-21 14:29:47.662 E/AndroidRuntime(30624): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.samwhited.opensharelocationplugin/com.samwhited.opensharelocationplugin.activities.ShareLocationActivity}: java.lang.IllegalArgumentException: provider doesn't exist: network
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2329)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.ActivityThread.access$900(ActivityThread.java:147)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.os.Looper.loop(Looper.java:135)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at java.lang.reflect.Method.invoke(Native Method)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
03-21 14:29:47.662 E/AndroidRuntime(30624): Caused by: java.lang.IllegalArgumentException: provider doesn't exist: network
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.os.Parcel.readException(Parcel.java:1544)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.os.Parcel.readException(Parcel.java:1493)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:584)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:867)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:459)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at com.samwhited.opensharelocationplugin.activities.LocationActivity.requestLocationUpdates(LocationActivity.java:34)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at com.samwhited.opensharelocationplugin.activities.ShareLocationActivity.onCreate(ShareLocationActivity.java:88)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.Activity.performCreate(Activity.java:5933)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
03-21 14:29:47.662 E/AndroidRuntime(30624): 	... 10 more
03-21 14:29:49.443 I/Process (30624): Sending signal. PID: 30624 SIG: 9
```

I don't have any wifi-based location providers (AOSP-only), and so "network" doesn't appear to be supported as a location source. (I'm guessing based on the error message.)

**Comment by SamWhited** [comment]
This should be fixed in the version I released this morning, actually. Thanks for reporting this!
